[package]
name = "distriptor-fixer"
version = "0.1.0"
authors = ["Mbobovnikov <45126908+Mbobovnikov@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
